---
name: Build manifest
inputs:
  target:
    required: true
runs:
  using: composite
  steps:
    - name: Set up TARGET
      run: echo "TARGET=${{ inputs.target }}" | tee $GITHUB_ENV
      shell: bash
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push manifests
      shell: bash
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: ./deploy-manifests.sh
